# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRoomFinderServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('semester', models.CharField(max_length=10)),
                ('weekday', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('occasions', models.CharField(max_length=10000)),
                ('room', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='university',
            field=models.CharField(default='kk', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombookedslot',
            name='university',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('university', 'campus', 'building', 'number')]),
        ),
    ]
